# Generated by Django 5.2.1 on 2025-05-20 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('report_path', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('report_date', models.DateField(auto_now_add=True)),
                ('audio_path', models.FileField(upload_to='audio/')),
                ('meeting_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_responsible', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='employees',
            field=models.ManyToManyField(related_name='meetings', through='meetings.MeetingEmployee', to=settings.AUTH_USER_MODEL),
        ),
    ]
