# Generated by Django 6.0.7 on 2026-07-17 23:38

import django.db.models.deletion
import meetings.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, default='', max_length=255, verbose_name='Тема')),
                ('report_path', models.FileField(blank=True, upload_to='reports/', verbose_name='Отчёт')),
                ('report_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('audio_path', models.FileField(upload_to=meetings.models.meeting_audio_upload_to, verbose_name='Аудиозапись')),
                ('meeting_date', models.DateField(blank=True, null=True, verbose_name='Дата совещания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Совещание',
                'verbose_name_plural': 'Совещания',
                'ordering': ['-meeting_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MeetingEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_responsible', models.BooleanField(default=False, verbose_name='Ответственный')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='meetings.meeting', verbose_name='Совещание')),
            ],
            options={
                'verbose_name': 'Участник совещания',
                'verbose_name_plural': 'Участники совещаний',
                'ordering': ['meeting_id', 'employee_id', 'id'],
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='employees',
            field=models.ManyToManyField(related_name='meetings', through='meetings.MeetingEmployee', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AddConstraint(
            model_name='meetingemployee',
            constraint=models.UniqueConstraint(condition=models.Q(('employee__isnull', False)), fields=('meeting', 'employee'), name='meeting_employee_unique_membership'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['meeting_date'], name='meeting_date_idx'),
        ),
    ]
